import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { RoutesModule } from './app.routes';
import { HttpModule } from '@angular/http';
import {ContainersClient, ContainerTypesClient} from "./autogenerated"
import { ContainerService } from './services/container.service';
import { ContainerTypeService } from './services/container-type.service';
import { HashLocationStrategy, LocationStrategy } from '@angular/common';
import { DataTableModule, SharedModule, DropdownModule } from 'primeng/primeng';

import { AppComponent } from './components/app.component';
import { ContainersComponent } from './components/containers.component';
import { ContainerDetailComponent } from './components/container-detail.component';


@NgModule({
    imports: [
        FormsModule,
        BrowserModule,
        RouterModule,
        HttpModule,
        RoutesModule,
        DataTableModule,
        SharedModule,
        DropdownModule
    ],
    providers: [
        ContainerService,
        ContainerTypeService,
        ContainersClient,
        ContainerTypesClient,
        { provide: LocationStrategy, useClass: HashLocationStrategy }
    ],
    declarations: [
        AppComponent,
        ContainersComponent,
        ContainerDetailComponent
    ],
    //exports: [AppComponent], remove, noone imports it
    bootstrap: [AppComponent]
})
export class AppModule { }