import { Injectable } from '@angular/core';
import {ContainerTypesClient, ContainerType} from "./../autogenerated"
import 'rxjs/add/operator/toPromise';

@Injectable()
export class ContainerTypeService {
    constructor(private client: ContainerTypesClient) {

    }

    getContainerTypes(): Promise<ContainerType[]> {
        return this.client.get()
            .toPromise()
            .then(
                response =>
                    response as ContainerType[]
            )
            .catch(this.handleError);
    }

   

    private handleError(error: any) {
        console.error('An error occurred', error);
        return Promise.reject(error.message || error);
    }
}